### ISSUE TITLE
FIx compatibility with Jupyter Notebook to show them in the webpage documentation.

### ISSUE THREAD

**Issue by pedrojuanbj** [pedrojuanbj/MLTSA#5]
Currently it shows an empty page for the notebooks, would have to be integrated correctly

**Comment by zwei21** [comment]
Fixed by keeping the jupyter notebooks inside of doc/source, which could be read from the online doc now but should be with better solution further, would arise other issues to concentrate on the notebook directory later
REF:4797de88349817531563c4101c765f2c59f7100e

**Comment by zwei21** [comment]
Fixed by keeping the jupyter notebooks inside of doc/source, which could be read from the online doc now but should be with better solution further, would arise other issues to concentrate on the notebook directory later
REF:4797de88349817531563c4101c765f2c59f7100e
